language: c
compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq irssi

script:
    - ./autogen.sh --with-proxy --with-bot
    - cat config.log
    - make
    - sudo make install

notifications:
    irc:
        channels:
            - "irc.freenode.net#irssi"
        on_success: always
        on_failure: always
